# yaml
# dev environment config
db:
  type: mysql
  user: go
  password: go2018
  host: 47.99.77.200:3306
  sid: goDB
  tableprefix: blog_
  maxidleconn: 10
  maxopenconn: 100
  dbdebug: true

server:
  runmode: debug
  httpprot: 8089
  readtimeout: 60
  wirtetimeout: 60

app:
  temp: empty
#
#jwt:
#  jwtsecret: $sfsadf$sdf8s
#  jwteffectivetime: 60
#
logs:
  logsrootpath: C:\\GOLib\\src\\go-web-scaffold\\logs
  logslevel: debug
  logsfilename: info.log
